"""add note to chef column to dishorder

Revision ID: 1ebba9e543fc
Revises: fcf14ee7625c
Create Date: 2023-04-18 22:00:58.177598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebba9e543fc'
down_revision = 'fcf14ee7625c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_to_chef', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dish_orders', schema=None) as batch_op:
        batch_op.drop_column('note_to_chef')

    # ### end Alembic commands ###
